### ISSUE TITLE
- [ ] Implementación en el Frontend haciendo uso de ReactJS evidenciando la navegación de acuerdo con los prototipos de alta fidelidad.

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo4_cv_ppi2020#15]

**Comment by JohnFlorez25** [comment]
@Richerson31 @jose-adamis11 @02alejo Recuerden que para dentro 8 días deben evidenciar avances en esta actividad donde tengan las interfaces en REACTJS de lo que se validó en el prototipo en alta fidelidad y recomendaciones de los jurados en la socialización.
El código debe estar en el repositorio del proyecto (o sea este repositorio) validar con el profesor Juan Perez para que les ayuden a realizar este proceso , les dejo un ejemplo de lo que se debe ir evidenciando.
![evidencia-repositorio](https://user-images.githubusercontent.com/22262727/94614810-5de5d900-026c-11eb-8e1c-294c6a3fccd1.jpeg)

**Comment by JohnFlorez25** [comment]
@Richerson31 @jose-adamis11 @02alejo Se pactó el compromiso de entregar esta actividad con el video evidenciando la navegabilidad en ReactJS para dentro de 8 días.

**Comment by jose-adamis11** [comment]
[https://codesandbox.io/s/silent-flower-9o5uo?ts=jxq1u7co](url)

**Comment by jose-adamis11** [comment]
[https://codesandbox.io/s/silent-flower-9o5uo?ts=jxq1u7co&file=/src/styles.css](url)

**Comment by jose-adamis11** [comment]
[https://codesandbox.io/s/silent-flower-9o5uo?file=/src/App.js](url)

**Comment by jose-adamis11** [comment]
https://codesandbox.io/s/silent-flower-9o5uo?file=/src/App.js
