### ISSUE TITLE
- [ ] Diseño del modelo entidad-relación

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo4_cv_ppi2020#16]

**Comment by JohnFlorez25** [comment]
@Richerson31 @jose-adamis11 @02alejo para dentro de 8 días deben tener la evidencia del Modelo entidad relación en la wiki, esta actividad la han venido desarrollando con el profesor Juan Perez y es ella quien les debe aprobar y validar dicho modelo. Adjunto imagen de ejemplo
![modelo-e-r](https://user-images.githubusercontent.com/22262727/94614854-6d652200-026c-11eb-860e-43eed24941aa.png)

**Comment by 02alejo** [comment]
@JohnFlorez25, ya finalizé el modelo de identidad relación
