### ISSUE TITLE
- [ ] Diseño del modelo lógico de datos

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo4_cv_ppi2020#18]

**Comment by JohnFlorez25** [comment]
@Richerson31 @jose-adamis11 @02alejo teniendo en cuenta la implementación del modelo entidad relación una vez validado entre el/la docente y el asesor, realizar la construcción del modelo lógico de datos par ala construcción de los scripts de la base de datos

**Comment by 02alejo** [comment]
![modelo](https://user-images.githubusercontent.com/66704329/97953612-15d83b80-1d6f-11eb-8d21-7ee824ba6e3e.png)
