### ISSUE TITLE
Diseñar el diagrama de espina de pescado

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo4_cv_ppi2020#2]

**Comment by jose-adamis11** [comment]
el diagrama de pescado ya esta realizado

**Comment by JohnFlorez25** [comment]
Identificar mejor el problema de acuerdo a las causas que se describen en el diagrama de espina de pescado

**Comment by JohnFlorez25** [comment]
@jose-adamis11 @02alejo @Richerson31 No se han generado las recomendaciones que se brindaron para mejorar el diagrama de espina de pescado, deben recordar que el problema no puede ser el título del proyecto y que las causas no pueden estar asociadas a un docente en particular, no podemos  permitir que esté sesgado el problema por una mala experiencia con un maestro en particular.
