### ISSUE TITLE
Declarar la situación de Problema

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo4_cv_ppi2020#3]

**Comment by jose-adamis11** [comment]
la declaración del problema ya esta realizada

**Comment by JohnFlorez25** [comment]
@jose-adamis11 @Richerson31 @02alejo La declaración de la situación del problema no debe estar sesgada por una mala experiencia con un docente, recuerden que al identificar un problema debemos generalizar en este caso para la materia a la cual ustedes quieren brindar herramientas de apoyo que ayuden a tener mejor resultados en dicho curso.
